"""Update models to new domain structure

Revision ID: 76fc53619193
Revises: acf8ed783469
Create Date: 2026-04-03 05:22:35.163436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '76fc53619193'
down_revision: Union[str, Sequence[str], None] = 'acf8ed783469'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('orders', sa.Column('status', sa.String(length=50), nullable=True))
    # op.drop_constraint(op.f('orders_ibfk_1'), 'orders', type_='foreignkey')
    # op.drop_constraint(op.f('orders_ibfk_2'), 'orders', type_='foreignkey')
    # op.create_foreign_key(None, 'orders', 'products', ['product_id'], ['product_id'], ondelete='CASCADE')
    # op.create_foreign_key(None, 'orders', 'buyers', ['buyer_id'], ['buyer_id'], ondelete='CASCADE')
    # op.add_column('subscriptions', sa.Column('subscription_id', sa.Integer(), autoincrement=True, nullable=False))
    # op.add_column('subscriptions', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('subscriptions_ibfk_2'), 'subscriptions', type_='foreignkey')
    op.drop_constraint(op.f('subscriptions_ibfk_1'), 'subscriptions', type_='foreignkey')
    op.drop_index(op.f('uq_buyer_seller'), table_name='subscriptions')
    op.create_foreign_key(None, 'subscriptions', 'buyers', ['buyer_id'], ['buyer_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'subscriptions', 'sellers', ['seller_id'], ['seller_id'], ondelete='CASCADE')
    op.drop_column('subscriptions', 'sub_id')
    op.add_column('wishlists', sa.Column('wishlist_id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('wishlists', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('wishlists_ibfk_2'), 'wishlists', type_='foreignkey')
    op.drop_constraint(op.f('wishlists_ibfk_1'), 'wishlists', type_='foreignkey')
    op.create_foreign_key(None, 'wishlists', 'buyers', ['buyer_id'], ['buyer_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'wishlists', 'products', ['product_id'], ['product_id'], ondelete='CASCADE')
    op.drop_column('wishlists', 'wish_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlists', sa.Column('wish_id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'wishlists', type_='foreignkey')
    op.drop_constraint(None, 'wishlists', type_='foreignkey')
    op.create_foreign_key(op.f('wishlists_ibfk_1'), 'wishlists', 'buyers', ['buyer_id'], ['buyer_id'])
    op.create_foreign_key(op.f('wishlists_ibfk_2'), 'wishlists', 'products', ['product_id'], ['product_id'])
    op.drop_column('wishlists', 'created_at')
    op.drop_column('wishlists', 'wishlist_id')
    op.add_column('subscriptions', sa.Column('sub_id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.create_foreign_key(op.f('subscriptions_ibfk_1'), 'subscriptions', 'buyers', ['buyer_id'], ['buyer_id'])
    op.create_foreign_key(op.f('subscriptions_ibfk_2'), 'subscriptions', 'sellers', ['seller_id'], ['seller_id'])
    op.create_index(op.f('uq_buyer_seller'), 'subscriptions', ['buyer_id', 'seller_id'], unique=True)
    op.drop_column('subscriptions', 'created_at')
    op.drop_column('subscriptions', 'subscription_id')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_ibfk_2'), 'orders', 'products', ['product_id'], ['product_id'])
    op.create_foreign_key(op.f('orders_ibfk_1'), 'orders', 'buyers', ['buyer_id'], ['buyer_id'])
    op.drop_column('orders', 'status')
    # ### end Alembic commands ###
