"""Initial schema

Revision ID: b6db10d17aa3
Revises: 
Create Date: 2026-04-03 02:34:03.129073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6db10d17aa3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyers',
    sa.Column('buyer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('buyer_id')
    )
    op.create_table('sellers',
    sa.Column('seller_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('residence', sa.String(length=100), nullable=True),
    sa.Column('experience', sa.Text(), nullable=True),
    sa.Column('repurchase_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('total_sales', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('seller_id')
    )
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('weight', sa.String(length=50), nullable=True),
    sa.Column('harvest_date', sa.Date(), nullable=True),
    sa.Column('taste_feature', sa.Text(), nullable=True),
    sa.Column('farmer_comment', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('voice_path', sa.String(length=255), nullable=True),
    sa.Column('final_description', sa.Text(), nullable=True),
    sa.Column('is_selling', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.seller_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('seller_images',
    sa.Column('image_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('img1', sa.String(length=255), nullable=True),
    sa.Column('img2', sa.String(length=255), nullable=True),
    sa.Column('img3', sa.String(length=255), nullable=True),
    sa.Column('img4', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.seller_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_table('subscriptions',
    sa.Column('sub_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.buyer_id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.seller_id'], ),
    sa.PrimaryKeyConstraint('sub_id'),
    sa.UniqueConstraint('buyer_id', 'seller_id', name='uq_buyer_seller')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.buyer_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('product_images',
    sa.Column('image_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('img1', sa.String(length=255), nullable=True),
    sa.Column('img2', sa.String(length=255), nullable=True),
    sa.Column('img3', sa.String(length=255), nullable=True),
    sa.Column('img4', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_table('wishlists',
    sa.Column('wish_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.buyer_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('wish_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wishlists')
    op.drop_table('product_images')
    op.drop_table('orders')
    op.drop_table('subscriptions')
    op.drop_table('seller_images')
    op.drop_table('products')
    op.drop_table('sellers')
    op.drop_table('buyers')
    # ### end Alembic commands ###
